In [19]:
import pandas as pd
import datetime as dt
import Frailty_Box.Utils
 
import locale
locale.setlocale(locale.LC_TIME,'')

ModuleNotFoundError: No module named 'Frailty_Box'

In [16]:
dataset = pd.read_csv('../output/hh101/habits_results.csv')

date_format = '%Y-%m-%d %H:%M:%S.%f'
dataset['start_validity'] = pd.to_datetime(dataset['start_validity'], format=date_format)
dataset['start_validity'] = dataset['start_validity'].dt.strftime("%d %b %Y")

dataset['end_validity'] = pd.to_datetime(dataset['end_validity'], format=date_format)
dataset['end_validity'] = dataset['end_validity'].dt.strftime("%d %b %Y")

dataset.sort_values(['accuracy'], ascending=False, inplace=True)

dataset

,episode,description,nb_occ,accuracy,start_validity,end_validity,nb_days_val
0,"['eat_breakfast', 'cook_breakfast']",{'8:41:22': '0:56:21'},56,0.947368,21 juil. 2012,17 sept. 2012,57
8,"['read', 'morning_meds']",{'7:28:48': '0:44:59'},25,0.892857,21 juil. 2012,18 ao没t 2012,27
11,['evening_meds'],{'22:46:48': '1:23:24'},55,0.883333,20 juil. 2012,17 sept. 2012,59
12,['dress'],{'23:46:51': '1:15:00'},102,0.830508,20 juil. 2012,17 sept. 2012,59
18,['groom'],{'11:18:21': '1:22:38'},24,0.785714,19 ao没t 2012,17 sept. 2012,28
2,"['sleep', 'personal_hygiene']",{'0:15:52': '0:40:32'},47,0.771930,21 juil. 2012,16 sept. 2012,57
19,['read'],{'9:20:30': '2:08:49'},28,0.740741,21 juil. 2012,17 ao没t 2012,27
9,['watch_tv'],{'10:21:25': '1:48:08'},151,0.724138,21 juil. 2012,17 sept. 2012,58
14,['wash_breakfast_dishes'],{'10:09:46': '1:17:57'},47,0.719298,22 juil. 2012,17 sept. 2012,57
3,"['watch_tv', 'toilet']",{'9:24:06': '1:59:28'},127,0.689655,20 juil. 2012,16 sept. 2012,58
5,"['toilet', 'leave_home']",{'14:02:38': '2:20:12'},68,0.649123,22 juil. 2012,17 sept. 2012,56
1,"['toilet', 'dress', 'bathe']",{'11:13:02': '1:07:35'},37,0.631579,21 juil. 2012,16 sept. 2012,56
6,['sleep_out_of_bed'],"{'7:55:20': '0:42:39', '20:37:40': '2:07:13'}",118,0.572650,20 juil. 2012,17 sept. 2012,58
7,"['watch_tv', 'enter_home']",{'16:44:05': '2:22:24'},55,0.559322,20 juil. 2012,17 sept. 2012,58
13,['toilet'],"{'8:03:34': '1:35:00', '13:07:57': '1:52:29'}",120,0.559322,20 juil. 2012,17 sept. 2012,59
4,"['sleep_out_of_bed', 'enter_home']","{'13:57:49': '1:47:43', '18:46:58': '0:13:07'}",87,0.548673,20 juil. 2012,14 sept. 2012,56
16,['morning_meds'],{'7:22:14': '1:09:34'},31,0.491228,22 juil. 2012,17 sept. 2012,57
10,['personal_hygiene'],"{'9:16:53': '2:01:38', '22:22:44': '1:31:11', ...",107,0.418994,20 juil. 2012,17 sept. 2012,59
20,['bathe'],{'10:48:21': '1:18:28'},22,0.370370,25 juil. 2012,17 sept. 2012,53
15,"['eat_dinner', 'cook_dinner']",{'18:47:05': '1:04:55'},22,0.363636,23 juil. 2012,16 sept. 2012,54
17,"['relax', 'enter_home']",{'13:50:37': '1:26:59'},22,0.361111,13 ao没t 2012,17 sept. 2012,35
21,['cook_breakfast'],{'9:03:12': '0:39:35'},23,0.327273,23 juil. 2012,16 sept. 2012,55
22,['relax'],{'7:14:05': '1:18:30'},70,0.271186,20 juil. 2012,17 sept. 2012,59
24,['sleep'],"{'1:15:40': '0:56:44', '4:18:08': '0:50:46'}",32,0.258929,22 juil. 2012,16 sept. 2012,56
25,['wash_dinner_dishes'],{'19:52:56': '1:51:45'},18,0.236364,23 juil. 2012,15 sept. 2012,54
23,"['leave_home', 'enter_home']","{'17:07:39': '1:43:09', '12:16:44': '0:56:07'}",29,0.233010,27 juil. 2012,16 sept. 2012,51
26,['cook_dinner'],{'18:08:32': '0:41:08'},19,0.218182,23 juil. 2012,16 sept. 2012,54
27,['cook_lunch'],{'13:32:04': '0:50:57'},18,0.206897,21 juil. 2012,17 sept. 2012,58