In [3]:
# import sys
# sys.path.append("../")
import pandas as pd
import numpy as np
import os
# from Utils import *
import datetime as dt
import matplotlib.pyplot as plt
import matplotlib.dates as dat


from sklearn.metrics import f1_score,confusion_matrix, accuracy_score

import seaborn as sns

sns.set_style('darkgrid')
sns.set(font_scale=1.4) # for label size

# from Behavior_Drift import *

In [4]:
data = pd.read_csv('../output/drift_toy_nb_drifts_results_w7_l10.csv')

data

,id,nb_drifts,nb_all_drifts_detected,nb_sleeping_drift_detected,nb_work_drift_detected,nb_eating_drift_detected
0,1,1,2,2,2,3
1,11,1,2,2,2,2
2,13,1,2,3,2,2
3,15,1,2,3,2,2
4,17,1,2,2,2,2
...,...,...,...,...,...,...
95,80,4,5,3,5,3
96,92,4,5,2,4,6
97,95,4,5,2,2,4
98,96,4,5,3,6,8
99,97,4,5,2,4,3

In [ ]:
dataset = pd.DataFrame(columns=['id', 'nb_clus', 'nb_clus_detected', 'type'])

for _, row in data.iterrows():
    toy_id = row['id']
    nb_clus = row['nb_drifts'] + 1
    
    listOfSeries = [pd.Series([toy_id, nb_clus, row['nb_all_drifts_detected'], 'MULTIPLE'], index=dfObj.columns),
                    pd.Series([toy_id, nb_clus, 'Tokyo', 'Japan'], index=dfObj.columns),
                    pd.Series([toy_id, nb_clus, 'Las Vegas', 'US'], index=dfObj.columns),
                    pd.Series([toy_id, nb_clus, 'Las Vegas', 'US'], index=dfObj.columns)]